version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki:/data/loki
    command: -config.file=./loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml    
    command: -config.file=./promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - loki
