version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - ./loki/data:/data/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./promtail/logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3200:3000"
    networks:
      - loki
